# Generated by Django 5.0.6 on 2024-07-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='aula_virtual/media/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
