# Generated by Django 5.0.6 on 2024-07-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('S', 'Sin registrar'), ('P', 'Presente'), ('A', 'Ausente'), ('R', 'Retrasado')], max_length=1),
        ),
    ]
