# Generated by Django 5.0.6 on 2024-06-29 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('jornada', models.CharField(choices=[('AM', 'Am'), ('PM', 'Pm')], max_length=2)),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('R', 'Retrasado')], max_length=1)),
                ('ID_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('certificado', models.FileField(upload_to='')),
                ('fecha_justificacion', models.DateField()),
                ('ID_apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaJustificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.asistencia')),
                ('ID_justificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.justificacion')),
            ],
        ),
    ]
