# Generated by Django 5.0.6 on 2024-07-03 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0002_alter_asistencia_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='ID_alumno',
            new_name='alumno',
        ),
    ]
