# Generated by Django 5.0.6 on 2024-07-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0002_asignatura_imagen_alter_material_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/aulavirtual/media/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
