# Generated by Django 5.0.6 on 2024-07-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0003_alter_asignatura_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='aula_virtual/uploads/'),
        ),
    ]
