# Generated by Django 5.0.6 on 2024-07-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0003_rename_id_alumno_asistencia_alumno'),
        ('aula_virtual', '0004_alter_material_archivo'),
    ]

    operations = [
    ]
