# Generated by Django 4.1.1 on 2024-07-05 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0003_rename_id_alumno_asistencia_alumno'),
        ('aula_virtual', '0004_notificacion'),
    ]

    operations = [
    ]
